service: yvm-github-gateway

plugins:
  - serverless-api-cloudfront

custom:
  apiCloudFront:
    compress: true
    querystring: none
    cookies: none

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: us-east-1

functions:
  app:
    handler: dist/lambda.init
    name: '${self:service}-app-router'
    timeout: 30
    events:
      - http:
          path: /
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
            allowCredentials: false
      - http:
          path: '{proxy+}'
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
            allowCredentials: false


